# Read in the Data

In [68]:
import pandas as pd
import numpy as np
energy_df = pd.read_csv("../datasets/raw/eia_data.csv")
energy_df.head()

,period,location,stateDescription,sectorid,sectorDescription,fueltypeid,fuelTypeDescription,ash-content,ash-content-units,consumption-for-eg,...,receipts-btu,receipts-btu-units,stocks,stocks-units,sulfur-content,sulfur-content-units,total-consumption,total-consumption-units,total-consumption-btu,total-consumption-btu-units
0,2024,PA,Pennsylvania,6,Industrial Non-CHP,PEL,petroleum liquids,NaN,percent,35.323,...,NaN,billion Btu,0.788,thousand barrels,NaN,percent,35.323,thousand barrels,0.20487,million MMBtu
1,2024,WI,Wisconsin,90,Electric Power Sector Non-CHP,WWW,wood and wood wastes,NaN,percent,0.000,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,0.000,thousand physical units,9.20345,million MMBtu
2,2024,WI,Wisconsin,90,Electric Power Sector Non-CHP,WOO,waste oil and other oils,NaN,percent,0.000,...,NaN,billion Btu,NaN,thousand barrels,NaN,percent,0.000,thousand barrels,0.00000,million MMBtu
3,2024,WI,Wisconsin,90,Electric Power Sector Non-CHP,NG,natural gas,NaN,percent,185752.941,...,168717.73089,billion Btu,NaN,thousand Mcf,NaN,percent,191287.171,thousand Mcf,198.00939,million MMBtu
4,2024,WI,Wisconsin,90,Electric Power Sector Non-CHP,COW,all coal products,5.0,percent,11662.838,...,192180.72036,billion Btu,NaN,thousand short tons,0.43,percent,11662.895,thousand short tons,210.85537,million MMBtu

# Data Exploration

Filter down to all sectors only. Our analysis won't be focused on individual sectors

In [69]:
# find unique sectors
energy_df["sectorDescription"].unique()

array(['Industrial Non-CHP', 'Electric Power Sector Non-CHP',
       'Industrial CHP', 'All Industrial', 'Electric Utility',
       'Commercial CHP', 'Commercial Non-CHP', 'IPP Non-CHP',
       'Independent Power Producers', 'Residential', 'All Commercial',
       'All Sectors', 'Electric Power', 'IPP CHP', 'Coal Consumption'],
      dtype=object)

In [70]:
# filter to just all sectors
energy_df = energy_df.loc[energy_df["sectorDescription"] == "All Sectors"]
energy_df.head()

,period,location,stateDescription,sectorid,sectorDescription,fueltypeid,fuelTypeDescription,ash-content,ash-content-units,consumption-for-eg,...,receipts-btu,receipts-btu-units,stocks,stocks-units,sulfur-content,sulfur-content-units,total-consumption,total-consumption-units,total-consumption-btu,total-consumption-btu-units
46,2024,ME,Maine,99,All Sectors,WWW,wood and wood wastes,NaN,percent,0.000,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,0.000,thousand physical units,37.01849,million MMBtu
47,2024,ME,Maine,99,All Sectors,DPV,estimated small scale solar photovoltaic,NaN,percent,NaN,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,NaN,thousand physical units,NaN,million MMBtu
53,2024,CT,Connecticut,99,All Sectors,NGO,natural gas & other gases,NaN,percent,180616.649,...,172355.49446,billion Btu,NaN,thousand Mcf,NaN,percent,188284.166,thousand Mcf,194.11429,million MMBtu
54,2024,CT,Connecticut,99,All Sectors,LFG,landfill gas,NaN,percent,132.166,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,132.166,thousand physical units,0.06469,million MMBtu
55,2024,CT,Connecticut,99,All Sectors,BIO,biomass,NaN,percent,1291.708,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,1291.708,thousand physical units,9.34429,million MMBtu

Find the fuel types that are in the data and filters down to only the ones we are interested in

In [71]:
energy_df["fuelTypeDescription"].unique()

array(['wood and wood wastes', 'estimated small scale solar photovoltaic',
       'natural gas & other gases', 'landfill gas', 'biomass',
       'solar photovoltaic', 'residual fuel oil', 'wind',
       'other renewables', 'nuclear', 'solar', 'petroleum coke',
       'fossil fuels', 'all coal products', 'all renewables', 'petroleum',
       'other', 'other gases', 'municiapl landfill gas',
       'coal, excluding waste coal', 'bituminous coal',
       'bituminous coal and synthetic coal', 'distillate fuel oil',
       'renewable', 'natural gas', 'petroleum liquids', 'lignite coal',
       'onshore wind turbine', 'estimated total solar',
       'estimated total solar photovoltaic', 'anthracite coal',
       'renewable waste products', 'subbituminous coal',
       'waste oil and other oils', 'conventional hydroelectric',
       'all fuels', 'biogenic municipal solid waste', 'solar thermal',
       'hydro-electric pumped storage', 'offshore wind turbine',
       'refined coal', 'waste coal', 'geothermal'], dtype=object)

In [72]:
#filter to relevant fuel types. We can change this later
fuel_types = ["petroleum", "natural gas", "all coal products", "onshore wind turbine", "estimated total solar", "nuclear"]
energy_df = energy_df[energy_df["fuelTypeDescription"].isin(fuel_types)]
energy_df.head()

,period,location,stateDescription,sectorid,sectorDescription,fueltypeid,fuelTypeDescription,ash-content,ash-content-units,consumption-for-eg,...,receipts-btu,receipts-btu-units,stocks,stocks-units,sulfur-content,sulfur-content-units,total-consumption,total-consumption-units,total-consumption-btu,total-consumption-btu-units
101,2024,NC,North Carolina,99,All Sectors,NUC,nuclear,NaN,percent,0.00000,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,0.00000,thousand physical units,453.08734,million MMBtu
107,2024,WI,Wisconsin,99,All Sectors,COW,all coal products,5.0,percent,11720.47500,...,192180.72036,billion Btu,NaN,thousand short tons,0.43,percent,11831.87400,thousand short tons,214.27383,million MMBtu
141,2024,NY,New York,99,All Sectors,PET,petroleum,NaN,percent,1033.90406,...,876.05975,billion Btu,NaN,thousand barrels,0.42,percent,1063.85906,thousand barrels,5.31540,million MMBtu
144,2024,NY,New York,99,All Sectors,NUC,nuclear,NaN,percent,0.00000,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,0.00000,thousand physical units,282.97034,million MMBtu
176,2024,NY,New York,99,All Sectors,COW,all coal products,NaN,percent,0.00000,...,NaN,billion Btu,NaN,thousand short tons,NaN,percent,0.00000,thousand short tons,0.00000,million MMBtu

Now, we filter to the years we want (2015-2023 since that is what we have cost data for)

In [73]:
#filter to relevant fuel types. We can change this later
years = [2015 + x for x in range(9)]
energy_df = energy_df[energy_df["period"].isin(years)]
energy_df.head()

,period,location,stateDescription,sectorid,sectorDescription,fueltypeid,fuelTypeDescription,ash-content,ash-content-units,consumption-for-eg,...,receipts-btu,receipts-btu-units,stocks,stocks-units,sulfur-content,sulfur-content-units,total-consumption,total-consumption-units,total-consumption-btu,total-consumption-btu-units
12718,2023,SD,South Dakota,99,All Sectors,COW,all coal products,5.14,percent,978.05600,...,17852.24449,billion Btu,NaN,thousand short tons,0.31,percent,1087.62400,thousand short tons,17.95756,million MMBtu
12827,2023,TX,Texas,99,All Sectors,NUC,nuclear,NaN,percent,0.00000,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,0.00000,thousand physical units,425.17591,million MMBtu
12874,2023,ME,Maine,99,All Sectors,PET,petroleum,NaN,percent,110.20781,...,2032.13051,billion Btu,NaN,thousand barrels,0.43,percent,231.93081,thousand barrels,1.41782,million MMBtu
12919,2023,IL,Illinois,99,All Sectors,PET,petroleum,NaN,percent,63.82500,...,452.92162,billion Btu,NaN,thousand barrels,NaN,percent,63.89400,thousand barrels,0.37522,million MMBtu
12930,2023,RI,Rhode Island,99,All Sectors,TSN,estimated total solar,NaN,percent,NaN,...,NaN,billion Btu,NaN,thousand physical units,NaN,percent,NaN,thousand physical units,NaN,million MMBtu

Checking now to see what the data looks like after that initial cleaning

In [74]:
#row counts
energy_df.drop_duplicates(inplace=True)
energy_df.shape[0]

1234

In [75]:
#find columns with missing values
energy_df.isna().sum()

period                             0
location                           0
stateDescription                   0
sectorid                           0
sectorDescription                  0
fueltypeid                         0
fuelTypeDescription                0
ash-content                      406
ash-content-units                  0
consumption-for-eg               221
consumption-for-eg-units           0
consumption-for-eg-btu           221
consumption-for-eg-btu-units       0
consumption-uto                  221
consumption-uto-units              0
consumption-uto-btu              221
consumption-uto-btu-units          0
cost                             967
cost-units                         0
cost-per-btu                    1200
cost-per-btu-units                 0
generation                         0
generation-units                   0
heat-content                     221
heat-content-units                 0
receipts                         319
receipts-units                     0
receipts-btu                     319
receipts-btu-units                 0
stocks                          1234
stocks-units                       0
sulfur-content                   395
sulfur-content-units               0
total-consumption                221
total-consumption-units            0
total-consumption-btu            221
total-consumption-btu-units        0
dtype: int64

Here we remove the rows where generation is 0 or missing

In [76]:
energy_df = energy_df[~(energy_df["generation"].isna() | (energy_df["generation"] == 0))]
energy_df.shape[0]

1218

Start dropping some columns that aren't needed.

We aren't focused on breaking down consumption by UTO and Energy Generation, only total, so we can drop those.

We can drop the stocks, heat content, and reciepts columns because we don't care about physical quantities of material.

We can also remove the stateDescription, because the location is enough. We can also remove the sectorid because sectorName is enough.

We can also remove the physical unit columns, because BTU allows for better comparisons.

We can drop all the costs since most are missing and we have that data from seds and LBNL

In [77]:
energy_df.drop(columns=["stateDescription", "sectorid", "consumption-for-eg", "consumption-for-eg-units", "consumption-for-eg-btu", "consumption-for-eg-btu-units", "consumption-uto", "consumption-uto-units", "consumption-uto-btu", "consumption-uto-btu-units", "total-consumption", "total-consumption-units", "heat-content", "heat-content-units", "receipts", "receipts-units", "receipts-btu", "receipts-btu-units", "stocks", "stocks-units", "cost", "cost-units", "cost-per-btu", "cost-per-btu-units"], inplace=True)
#rename location to "stateID" to match the other data
energy_df = energy_df.rename(columns={"location": "stateid"})
energy_df.isna().sum()

period                           0
stateid                          0
sectorDescription                0
fueltypeid                       0
fuelTypeDescription              0
ash-content                    399
ash-content-units                0
generation                       0
generation-units                 0
sulfur-content                 388
sulfur-content-units             0
total-consumption-btu          221
total-consumption-btu-units      0
dtype: int64

# Reading in Price Data

Some of the price data (Solar and wind) is already in price per MWh

The fossil fuel price data is in total expenditure, so we will need to make cost per MWh based on expenditure/generation.

In [78]:
solar_price_df = pd.read_csv("../datasets/cleaned/solar_cost_per_state.csv")
solar_price_df.head()

  State  Year  Price ($/MWh)
0    AL  2015      60.752500
1    AL  2016      51.520000
2    AL  2017      36.152000
3    AL  2018      28.674000
4    AL  2019      25.125556

In [79]:
wind_price_df = pd.read_csv("../datasets/cleaned/wind_cost_per_state.csv")
wind_price_df.head()

  State  Year  Real 2024$/MWh
0    AL  2015             NaN
1    AL  2016             NaN
2    AL  2017            20.0
3    AL  2018             NaN
4    AL  2019            20.0

I describe it more in the seds cleaning, but here each column is a seds datapoint, either cost statistic or co2 statistic for a certain type of fuel. 

The cost is in Millions of Dollars.

In [80]:
seds_df = pd.read_csv("../datasets/cleaned/seds_cleaned.csv")
seds_df.head()

  stateid  period  CLEIV  CLTCE  FFTCE  NGEIV  NNTCE  NUEGV  PAEIV  PMTCE
0      AK    2016   29.7    1.6   33.4  187.7   16.9    0.0   67.0   14.9
1      AK    2017   28.4    1.6   33.7  204.8   17.6    0.0   81.4   14.6
2      AK    2018   34.0    1.7   34.5  170.6   17.7    0.0   86.3   15.2
3      AK    2019   38.7    1.7   34.3  170.3   17.6    0.0   79.0   15.1
4      AK    2020   39.4    1.8   36.1  147.1   19.1    0.0   68.0   15.1

# Bringing the Data Together

Now we can add the solar and wind price per MWh and the raw cost for the othe fuels to the data.

In [81]:
energy_df["Cost ($/MWh)"] = np.nan
solar_only = energy_df[energy_df["fuelTypeDescription"] == "estimated total solar"].copy()

solar_merged = solar_only.merge(
    solar_price_df.rename(columns={"State": "stateid", "Year": "period"}),
    on=["stateid", "period"],
    how="left"
)
energy_df.loc[energy_df["fuelTypeDescription"] == "estimated total solar", "Cost ($/MWh)"] = solar_merged["Price ($/MWh)"].values

In [82]:
wind_only = energy_df[energy_df["fuelTypeDescription"] == "onshore wind turbine"].copy()

wind_merged = wind_only.merge(
    wind_price_df.rename(columns={"State": "stateid", "Year": "period"}),
    on=["stateid", "period"],
    how="left"
)

energy_df.loc[energy_df["fuelTypeDescription"] == "onshore wind turbine", "Cost ($/MWh)"] = wind_merged["Real 2024$/MWh"].values

Here we add the SEDS data of fuel type expenditure to a column called "raw cost" since this is in millions of dollars, not in $/MWh

We also add the CO2 emissions data

In [83]:
energy_df["Raw Cost (Millions of $)"] = np.nan
energy_df["CO2 Emissions (Million Metric Tons)"] = np.nan
coal_only = energy_df[energy_df["fuelTypeDescription"] == "all coal products"].copy()
coal_merged = coal_only.merge(
    seds_df,
    on=["stateid", "period"],
    how="left"
)
energy_df.loc[energy_df["fuelTypeDescription"] == "all coal products", "Raw Cost (Millions of $)"] = coal_merged["CLEIV"].values
energy_df.loc[energy_df["fuelTypeDescription"] == "all coal products", "CO2 Emissions (Million Metric Tons)"] = coal_merged["CLTCE"].values

petroleum_only = energy_df[energy_df["fuelTypeDescription"] == "petroleum"].copy()
petroleum_merged = petroleum_only.merge(
    seds_df,
    on=["stateid", "period"],
    how="left"
)
energy_df.loc[energy_df["fuelTypeDescription"] == "petroleum", "Raw Cost (Millions of $)"] = petroleum_merged["PAEIV"].values
energy_df.loc[energy_df["fuelTypeDescription"] == "petroleum", "CO2 Emissions (Million Metric Tons)"] = petroleum_merged["PMTCE"].values

nuclear_only = energy_df[energy_df["fuelTypeDescription"] == "nuclear"].copy()
nuclear_merged = nuclear_only.merge(
    seds_df,
    on=["stateid", "period"],
    how="left"
)
energy_df.loc[energy_df["fuelTypeDescription"] == "nuclear", "Raw Cost (Millions of $)"] = nuclear_merged["NUEGV"].values

ng_only = energy_df[energy_df["fuelTypeDescription"] == "natural gas"].copy()
ng_merged = ng_only.merge(
    seds_df,
    on=["stateid", "period"],
    how="left"
)
energy_df.loc[energy_df["fuelTypeDescription"] == "natural gas", "Raw Cost (Millions of $)"] = ng_merged["NGEIV"].values
energy_df.loc[energy_df["fuelTypeDescription"] == "natural gas", "CO2 Emissions (Million Metric Tons)"] = ng_merged["NNTCE"].values

Quick check to see what it looks like

In [84]:
energy_df.head()

,period,stateid,sectorDescription,fueltypeid,fuelTypeDescription,ash-content,ash-content-units,generation,generation-units,sulfur-content,sulfur-content-units,total-consumption-btu,total-consumption-btu-units,Cost ($/MWh),Raw Cost (Millions of $),CO2 Emissions (Million Metric Tons)
12718,2023,SD,All Sectors,COW,all coal products,5.14,percent,1562.74207,thousand megawatthours,0.31,percent,17.95756,million MMBtu,NaN,40.5,2.1
12827,2023,TX,All Sectors,NUC,nuclear,NaN,percent,40679.87000,thousand megawatthours,NaN,percent,425.17591,million MMBtu,NaN,250.2,NaN
12874,2023,ME,All Sectors,PET,petroleum,NaN,percent,67.15373,thousand megawatthours,0.43,percent,1.41782,million MMBtu,NaN,17.1,12.3
12919,2023,IL,All Sectors,PET,petroleum,NaN,percent,26.28754,thousand megawatthours,NaN,percent,0.37522,million MMBtu,NaN,8.7,76.3
12930,2023,RI,All Sectors,TSN,estimated total solar,NaN,percent,1026.60855,thousand megawatthours,NaN,percent,NaN,million MMBtu,NaN,NaN,NaN

# Finishing Cleaning

We check what is NA and what outliers there are. We clean the column names and remove things we don't need

Here we can see that solar and wind are still missing some costs, as are the other fuels.

We will have a better idea once we derive cost per megawatt hour using the raw cost

In [85]:
energy_df.isna().sum(), energy_df["fuelTypeDescription"].value_counts(), energy_df.shape[0]

(period                                   0
 stateid                                  0
 sectorDescription                        0
 fueltypeid                               0
 fuelTypeDescription                      0
 ash-content                            399
 ash-content-units                        0
 generation                               0
 generation-units                         0
 sulfur-content                         388
 sulfur-content-units                     0
 total-consumption-btu                  221
 total-consumption-btu-units              0
 Cost ($/MWh)                           881
 Raw Cost (Millions of $)               418
 CO2 Emissions (Million Metric Tons)    555
 dtype: int64,
 fuelTypeDescription
 petroleum                228
 natural gas              222
 estimated total solar    221
 all coal products        213
 onshore wind turbine     197
 nuclear                  137
 Name: count, dtype: int64,
 1218)

In [86]:
energy_df.describe()

,period,ash-content,generation,sulfur-content,total-consumption-btu,Cost ($/MWh),Raw Cost (Millions of $),CO2 Emissions (Million Metric Tons)
count,1218.000000,819.000000,1218.000000,830.000000,997.000000,337.000000,800.000000,663.000000
mean,2019.317734,2.151404,13719.256780,0.465735,152.540228,36.467761,412.940125,32.843137
std,2.317104,4.144487,25199.190056,1.107974,249.008661,15.236307,923.799378,40.903955
min,2016.000000,0.000000,-188.632270,0.000000,0.000280,13.250000,0.000000,0.000000
25%,2017.000000,0.000000,207.047635,0.000000,3.203700,27.477500,17.375000,10.650000
50%,2019.000000,0.000000,3023.101300,0.000000,53.230420,33.000000,131.600000,21.500000
75%,2021.000000,2.000000,17218.947108,0.370000,201.868080,43.700000,484.175000,39.300000
max,2023.000000,26.660000,256140.179820,6.010000,2324.035630,122.500000,14914.800000,329.900000

## Fixing Units in Data

Here we can look at what the units are for each column we have a separate units column for. Since the units are the same for all rows, we can remove that column and just change the column name to include the units.

In [87]:
print(energy_df["total-consumption-btu-units"].value_counts())
print(energy_df["ash-content-units"].value_counts())
print(energy_df["generation-units"].value_counts())
print(energy_df["sulfur-content-units"].value_counts())

total-consumption-btu-units
million MMBtu    1218
Name: count, dtype: int64
ash-content-units
percent    1218
Name: count, dtype: int64
generation-units
thousand megawatthours    1218
Name: count, dtype: int64
sulfur-content-units
percent    1218
Name: count, dtype: int64

In [88]:
energy_df = energy_df.rename(columns={"period": "Year", 
                                      "stateid": "State", 
                                      "ash-content": "Ash Content (%)", 
                                      "generation": "Generation (Thousands of MWh)", 
                                      "sulfur-content": "Sulfur Content (%)",
                                      "total-consumption-btu": "Total Consumption (millions of MMBtu)"
                                      })
energy_df.head()

,Year,State,sectorDescription,fueltypeid,fuelTypeDescription,Ash Content (%),ash-content-units,Generation (Thousands of MWh),generation-units,Sulfur Content (%),sulfur-content-units,Total Consumption (millions of MMBtu),total-consumption-btu-units,Cost ($/MWh),Raw Cost (Millions of $),CO2 Emissions (Million Metric Tons)
12718,2023,SD,All Sectors,COW,all coal products,5.14,percent,1562.74207,thousand megawatthours,0.31,percent,17.95756,million MMBtu,NaN,40.5,2.1
12827,2023,TX,All Sectors,NUC,nuclear,NaN,percent,40679.87000,thousand megawatthours,NaN,percent,425.17591,million MMBtu,NaN,250.2,NaN
12874,2023,ME,All Sectors,PET,petroleum,NaN,percent,67.15373,thousand megawatthours,0.43,percent,1.41782,million MMBtu,NaN,17.1,12.3
12919,2023,IL,All Sectors,PET,petroleum,NaN,percent,26.28754,thousand megawatthours,NaN,percent,0.37522,million MMBtu,NaN,8.7,76.3
12930,2023,RI,All Sectors,TSN,estimated total solar,NaN,percent,1026.60855,thousand megawatthours,NaN,percent,NaN,million MMBtu,NaN,NaN,NaN

We can now drop the units columns along with the sector description, since its the same value for all.

In [89]:
energy_df.drop(["sectorDescription", "ash-content-units", "generation-units", "sulfur-content-units","total-consumption-btu-units"], 
               axis=1,
               inplace=True)
energy_df.head()

,Year,State,fueltypeid,fuelTypeDescription,Ash Content (%),Generation (Thousands of MWh),Sulfur Content (%),Total Consumption (millions of MMBtu),Cost ($/MWh),Raw Cost (Millions of $),CO2 Emissions (Million Metric Tons)
12718,2023,SD,COW,all coal products,5.14,1562.74207,0.31,17.95756,NaN,40.5,2.1
12827,2023,TX,NUC,nuclear,NaN,40679.87000,NaN,425.17591,NaN,250.2,NaN
12874,2023,ME,PET,petroleum,NaN,67.15373,0.43,1.41782,NaN,17.1,12.3
12919,2023,IL,PET,petroleum,NaN,26.28754,NaN,0.37522,NaN,8.7,76.3
12930,2023,RI,TSN,estimated total solar,NaN,1026.60855,NaN,NaN,NaN,NaN,NaN

# Save to File

In [90]:
energy_df.to_csv(f"../datasets/cleaned/cleaned_combined_data.csv", index=False)

# Adding Derived Data

Read in the derived data

In [91]:
ppmwh_df = pd.read_csv("../derived_data/price_per_mwh.csv")
ppmwh_df.head()

,Year,State,fuelTypeDescription,Generation_MWh,Expenditure_USD,Price_per_MWh
0,2016,AK,natural gas,3040487.30,187700000.0,61.733525
1,2016,AK,petroleum,831329.64,67000000.0,80.593782
2,2016,AL,all coal products,34258405.52,801600000.0,23.398637
3,2016,AL,petroleum,45832.37,3700000.0,80.728970
4,2016,AR,petroleum,42363.25,4300000.0,101.503072

We aren't interested in generation or expenditure since its already in our data

In [92]:
ppmwh_df.drop(columns=["Generation_MWh", "Expenditure_USD"], inplace=True)
ppmwh_df = ppmwh_df.rename(columns={"Price_per_MWh" : "Cost ($/MWh)"})
ppmwh_df.head()

   Year State fuelTypeDescription  Cost ($/MWh)
0  2016    AK         natural gas     61.733525
1  2016    AK           petroleum     80.593782
2  2016    AL   all coal products     23.398637
3  2016    AL           petroleum     80.728970
4  2016    AR           petroleum    101.503072

In [93]:
energy_df = energy_df.merge(
    ppmwh_df,
    on=["Year", "State", "fuelTypeDescription"],
    how="left"
)
#creates two cost columns, so we need to manually fill in missing with new derived data
energy_df["Cost ($/MWh)"] = energy_df["Cost ($/MWh)_x"].fillna(energy_df["Cost ($/MWh)_y"])
energy_df.drop(["Cost ($/MWh)_x", "Cost ($/MWh)_y"], axis=1, inplace=True)

# Final Look/Save

With the derived, the missing values are much more acceptable. Only 223 missing cost/mwh values

In [94]:
energy_df.isna().sum()

Year                                       0
State                                      0
fueltypeid                                 0
fuelTypeDescription                        0
Ash Content (%)                          399
Generation (Thousands of MWh)              0
Sulfur Content (%)                       388
Total Consumption (millions of MMBtu)    221
Raw Cost (Millions of $)                 418
CO2 Emissions (Million Metric Tons)      555
Cost ($/MWh)                             223
dtype: int64

In [95]:
energy_df.describe()

,Year,Ash Content (%),Generation (Thousands of MWh),Sulfur Content (%),Total Consumption (millions of MMBtu),Raw Cost (Millions of $),CO2 Emissions (Million Metric Tons),Cost ($/MWh)
count,1218.000000,819.000000,1218.000000,830.000000,997.000000,800.000000,663.000000,995.000000
mean,2019.317734,2.151404,13719.256780,0.465735,152.540228,412.940125,32.843137,59.553637
std,2.317104,4.144487,25199.190056,1.107974,249.008661,923.799378,40.903955,79.864739
min,2016.000000,0.000000,-188.632270,0.000000,0.000280,0.000000,0.000000,0.000000
25%,2017.000000,0.000000,207.047635,0.000000,3.203700,17.375000,10.650000,23.648602
50%,2019.000000,0.000000,3023.101300,0.000000,53.230420,131.600000,21.500000,32.518143
75%,2021.000000,2.000000,17218.947108,0.370000,201.868080,484.175000,39.300000,55.430637
max,2023.000000,26.660000,256140.179820,6.010000,2324.035630,14914.800000,329.900000,1616.758210

In [96]:
energy_df.to_csv(f"../datasets/cleaned/cleaned_combined_data_with_derived.csv", index=False)